### ISSUE TITLE
Error "No matched device"

### ISSUE THREAD

**Issue by autolog** [GledholtHall/beta-3#10]
Maybe related to issue #9 ?

When I publish:
   
> Hubitat Bridge Debug            >>> Published to 'home-1': Topic='homie/home-1/study-socket-elgato-key-light/onoff/set', Payload='true'
>    Hubitat Bridge Debug            Received from 'home-1': Topic='[u'homie', u'home-1', u'study-socket-elgato-key-light', u'onoff', u'set']', Payload='true'

I get the following error in MQTT log:
> app:1322022-01-24 17:45:15.951 errorMQTT: No matched device for Study Socket Elgato Key Light

However, if I turn the device **on** or **off** in Hubitat, it publishes to MQTT and Indigo updates its device. So it seems that for some reason, the MQTT App in HE doesn't recognise the device, even though it is one it publishes.

MQTT Explorer for the device, looks like this:
![MQTT_Explorer_Definitions_V3](https://user-images.githubusercontent.com/11138074/150837531-ed69e592-b6a7-4065-8b18-1b3ea128a4e2.png)

**Comment by GledholtHall** [comment]
Will take a look later

**Comment by GledholtHall** [comment]
This is awkward for me to replicate as the only way to create such a ZigBee device is if you have one and I don't.

`app:1322022-01-24 17:45:15.951 errorMQTT: No matched device for Study Socket Elgato Key Light`

This means it can't find the device "Study Socket Elgato Key Light" and it searches all the names of the enabled devices in the dropdowns - can you tell me in which dropdown category this is enabled for publishing ?  e.g. 'Sensors' 'Dimmers' , 'Everything' and perhaps include a screengrab of that dropdown.  It may be enabled in several dropdowns.

**Comment by GledholtHall** [comment]
I think I can reproduce this error - investigating

**Comment by GledholtHall** [comment]
fixed pre24b

**Comment by autolog** [comment]
Installed the new APP: // 25/JAN/2022 from 192.168.1.3 - beta 3e pre24b and
installed correct MQTT Child Driver: // 29/9/2021 from 192.168.1.237  pre22

I am still getting the "no matched device" error: **app:1322022-01-25 10:53:12.632 errorMQTT: No matched device for Study Socket Elgato Key Light**

Thats when I publish this to MQTT: **>>> Published to 'home-1': Topic='homie/home-1/study-socket-elgato-key-light/onoff/set', Payload='true'**

**Comment by GledholtHall** [comment]
Strange as I did find the issue and fix it - I will manually enter your device details here (there is no easy cut and paste way from MQTT Explorer and see how I get on.
